### ISSUE TITLE
How to use I get error when i try

### ISSUE THREAD

**Issue by ThreeMinutesFix** [mbahArip/next-gdrive-index#24]
![photo_2024-06-17_19-15-38](https://github.com/mbahArip/next-gdrive-index/assets/103521732/954fe1e3-0ce4-4971-8194-e39eb42fdbab)
what could be the issue, Any video guide? i am using it to make index and get direct links

![image](https://github.com/mbahArip/next-gdrive-index/assets/103521732/1b0ff0a6-5468-463a-b997-0dd675eca6ed)

**Comment by mbahArip** [comment]
Can you copy the whole build log here?

**Comment by ThreeMinutesFix** [comment]
certianly

[19:22:22.092] Running build in Washington, D.C., USA (East) – iad1
[19:22:22.417] Cloning github.com/ThreeMinutesFix/next-gdrive-index (Branch: main, Commit: fcdac1f)
[19:22:23.032] Previous build cache not available
[19:22:23.147] Cloning completed: 726.028ms
[19:22:23.811] Running "vercel build"
[19:22:24.811] Vercel CLI 34.2.7
[19:22:25.444] Installing dependencies...
[19:22:25.833] yarn install v1.22.19
[19:22:25.981] [1/4] Resolving packages...
[19:22:27.083] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog@5.0.1: This package is no longer supported.
[19:22:27.101] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[19:22:27.182] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog > gauge@3.0.2: This package is no longer supported.
[19:22:27.221] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog > are-we-there-yet@2.0.0: This package is no longer supported.
[19:22:27.362] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
[19:22:27.436] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[19:22:43.604] warning eslint > @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
[19:22:43.672] warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[19:22:43.743] warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[19:22:47.439] [2/4] Fetching packages...
[19:24:33.229] [3/4] Linking dependencies...
[19:24:33.245] warning " > plyr-react@5.3.0" has unmet peer dependency "plyr@^3.7.7".
[19:24:33.258] warning "react-hot-toast > goober@2.1.14" has unmet peer dependency "csstype@^3.0.10".
[19:24:33.258] warning " > react-popper@2.3.0" has unmet peer dependency "@popperjs/core@^2.0.0".
[19:24:33.262] warning "eslint-config-next > @typescript-eslint/parser@7.2.0" has incorrect peer dependency "eslint@^8.56.0".
[19:24:55.639] [4/4] Building fresh packages...
[19:25:02.912] success Saved lockfile.
[19:25:02.951] Done in 157.11s.
[19:25:03.099] Detected Next.js version: 14.2.4
[19:25:03.102] Running "yarn run build"
[19:25:03.563] yarn run v1.22.19
[19:25:03.660] $ next build
[19:25:06.985] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[19:25:06.986] This information is used to shape Next.js' roadmap and prioritize features.
[19:25:06.986] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[19:25:06.986] https://nextjs.org/telemetry
[19:25:06.986] 
[19:25:07.157]   ▲ Next.js 14.2.4
[19:25:07.166] 
[19:25:07.332]    Creating an optimized production build ...
[19:27:28.788]  ✓ Compiled successfully
[19:27:28.793]    Linting and checking validity of types ...
[19:28:23.367]    Collecting page data ...
[19:28:25.809] TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
[19:28:25.809]     at Function.from (node:buffer:319:9)
[19:28:25.809]     at 2942 (/vercel/path0/.next/server/chunks/833.js:1:22023)
[19:28:25.809]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
[19:28:25.809]     at 11833 (/vercel/path0/.next/server/chunks/833.js:1:532)
[19:28:25.809]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
[19:28:25.809]     at 92145 (/vercel/path0/.next/server/app/api/raw/[...rest]/route.js:1:1611)
[19:28:25.809]     at t (/vercel/path0/.next/server/webpack-runtime.js:1:128)
[19:28:25.809]     at t (/vercel/path0/.next/server/app/api/raw/[...rest]/route.js:1:3240)
[19:28:25.809]     at /vercel/path0/.next/server/app/api/raw/[...rest]/route.js:1:3287
[19:28:25.809]     at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1206) {
[19:28:25.809]   code: 'ERR_INVALID_ARG_TYPE'
[19:28:25.809] }
[19:28:25.809] 
[19:28:25.809] > Build error occurred
[19:28:25.809] Error: Failed to collect page data for /api/raw/[...rest]
[19:28:25.809]     at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
[19:28:25.809]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[19:28:25.809]   type: 'Error'
[19:28:25.809] }
[19:28:26.113] error Command failed with exit code 1.
[19:28:26.114] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[19:28:26.190] Error: Command "yarn run build" exited with 1
[19:28:27.334]

**Comment by mbahArip** [comment]
I just checked your fork.
Make sure you're using your own config file with encrypted root / shared drive id, also make sure you set the env inside project settings in vercel.

**Comment by ThreeMinutesFix** [comment]
yes i setted the key but still its shows same error even though key setting.  about root or share id i have to check

**Comment by mbahArip** [comment]
Encryption method are updated in the latest version
You can try to update the repository, and read the [migration guide](https://drive-demo.mbaharip.com/ngdi-internal/deploy#migration)

Video guide will be uploaded ASAP

**Comment by ThreeMinutesFix** [comment]
Thanks sir
