### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pk3011** [mbahArip/next-gdrive-index#25]
[10:27:51.042] Running build in Washington, D.C., USA (East) – iad1
[10:27:51.187] Cloning github.com/pk3011/vercel-index (Branch: main, Commit: e0fdb15)
[10:27:51.507] Cloning completed: 319.604ms
[10:27:51.531] Previous build cache not available
[10:27:51.786] Running "vercel build"
[10:27:52.365] Vercel CLI 34.2.7
[10:27:52.737] Installing dependencies...
[10:27:53.023] yarn install v1.22.19
[10:27:53.111] [1/4] Resolving packages...
[10:27:54.257] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog@5.0.1: This package is no longer supported.
[10:27:54.267] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[10:27:54.284] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog > gauge@3.0.2: This package is no longer supported.
[10:27:54.289] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog > are-we-there-yet@2.0.0: This package is no longer supported.
[10:27:54.305] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
[10:27:54.364] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[10:28:06.581] warning eslint > @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
[10:28:06.653] warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[10:28:06.682] warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[10:28:08.333] [2/4] Fetching packages...
[10:28:37.654] [3/4] Linking dependencies...
[10:28:37.669] warning " > plyr-react@5.3.0" has unmet peer dependency "plyr@^3.7.7".
[10:28:37.676] warning "react-hot-toast > goober@2.1.14" has unmet peer dependency "csstype@^3.0.10".
[10:28:37.676] warning " > react-popper@2.3.0" has unmet peer dependency "@popperjs/core@^2.0.0".
[10:28:37.684] warning "eslint-config-next > @typescript-eslint/parser@7.2.0" has incorrect peer dependency "eslint@^8.56.0".
[10:28:47.470] [4/4] Building fresh packages...
[10:28:49.741] success Saved lockfile.
[10:28:49.750] Done in 56.73s.
[10:28:49.800] Detected Next.js version: 14.2.4
[10:28:49.802] Running "yarn run build"
[10:28:49.986] yarn run v1.22.19
[10:28:50.020] $ next build
[10:28:50.725] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[10:28:50.726] This information is used to shape Next.js' roadmap and prioritize features.
[10:28:50.726] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[10:28:50.726] https://nextjs.org/telemetry
[10:28:50.726] 
[10:28:50.790]   ▲ Next.js 14.2.4
[10:28:50.791]   - Environments: .env
[10:28:50.792] 
[10:28:50.860]    Creating an optimized production build ...
[10:29:48.186]  ✓ Compiled successfully
[10:29:48.187]    Linting and checking validity of types ...
[10:30:10.173]    Collecting page data ...
[10:30:12.475]    Generating static pages (0/4) ...
[10:30:14.697]    Generating static pages (1/4) 
[10:30:14.699]    Generating static pages (2/4) 
[10:30:15.372]    Generating static pages (3/4) 
[10:30:15.375] File not found: .
[10:30:15.375] Error: File not found: .
[10:30:15.375]     at T (/vercel/path0/.next/server/chunks/833.js:1:11566)
[10:30:15.376]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:30:15.376]     at async Promise.all (index 1)
[10:30:15.376]     at async l (/vercel/path0/.next/server/app/page.js:1:7755) {
[10:30:15.376]   digest: '1603866463'
[10:30:15.376] }
[10:30:15.376] File not found: .
[10:30:15.377] File not found: .
[10:30:15.377] Error: File not found: .
[10:30:15.377]     at T (/vercel/path0/.next/server/chunks/833.js:1:11566)
[10:30:15.377]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:30:15.377]     at async Promise.all (index 1)
[10:30:15.377]     at async l (/vercel/path0/.next/server/app/page.js:1:7755) {
[10:30:15.377]   digest: '1603866463'
[10:30:15.377] }
[10:30:15.377] Error: File not found: .
[10:30:15.377]     at T (/vercel/path0/.next/server/chunks/833.js:1:11566)
[10:30:15.377]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:30:15.377]     at async Promise.all (index 1)
[10:30:15.377]     at async l (/vercel/path0/.next/server/app/page.js:1:7755) {
[10:30:15.377]   digest: '1603866463'
[10:30:15.377] }
[10:30:15.377] 
[10:30:15.377] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[10:30:15.377] 
[10:30:15.377] Error: File not found: .
[10:30:15.377]     at T (/vercel/path0/.next/server/chunks/833.js:1:11566)
[10:30:15.377]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:30:15.377]     at async Promise.all (index 1)
[10:30:15.377]     at async l (/vercel/path0/.next/server/app/page.js:1:7755)
[10:30:15.377] File not found: .
[10:30:15.378]  ✓ Generating static pages (4/4)
[10:30:15.410] 
[10:30:15.411] > Export encountered errors on following paths:
[10:30:15.411] 	/page: /
[10:30:15.518] error Command failed with exit code 1.
[10:30:15.519] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[10:30:15.541] Error: Command "yarn run build" exited with 1
[10:30:16.335]

**Comment by mbahArip** [comment]
1. Make sure you've set the env inside Vercel deployment settings
2. If you're using the configurator, there's a bug where it generated the wrong encrypted root / shared drive ID. So you need to re-encrypt the ID yourself using the encrypt API routes. (`https://drive-demo.mbaharip.com/api/internal/encrypt?q=<ID>&key=<ENCRYPTION_KEY>`)
