### ISSUE TITLE
error, sorry for disturb

### ISSUE THREAD

**Issue by pk3011** [mbahArip/next-gdrive-index#26]
[09:14:46.995] Running build in Washington, D.C., USA (East) – iad1
[09:14:47.206] Cloning github.com/pk3011/next-gdrive-index (Branch: main, Commit: 899960a)
[09:14:47.633] Previous build cache not available
[09:14:47.827] Cloning completed: 620.238ms
[09:14:48.411] Running "vercel build"
[09:14:49.574] Vercel CLI 34.2.8
[09:14:50.312] Installing dependencies...
[09:14:50.961] yarn install v1.22.19
[09:14:51.204] [1/4] Resolving packages...
[09:14:52.743] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog@5.0.1: This package is no longer supported.
[09:14:52.760] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[09:14:52.808] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog > are-we-there-yet@2.0.0: This package is no longer supported.
[09:14:52.811] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog > gauge@3.0.2: This package is no longer supported.
[09:14:52.891] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
[09:14:52.995] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[09:15:07.637] warning eslint > @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
[09:15:07.691] warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[09:15:07.726] warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[09:15:09.524] [2/4] Fetching packages...
[09:15:39.060] [3/4] Linking dependencies...
[09:15:39.075] warning " > plyr-react@5.3.0" has unmet peer dependency "plyr@^3.7.7".
[09:15:39.078] warning "react-hot-toast > goober@2.1.14" has unmet peer dependency "csstype@^3.0.10".
[09:15:39.079] warning " > react-popper@2.3.0" has unmet peer dependency "@popperjs/core@^2.0.0".
[09:15:39.079] warning "eslint-config-next > @typescript-eslint/parser@7.2.0" has incorrect peer dependency "eslint@^8.56.0".
[09:15:51.047] [4/4] Building fresh packages...
[09:15:53.338] success Saved lockfile.
[09:15:53.347] Done in 62.39s.
[09:15:53.404] Detected Next.js version: 14.2.4
[09:15:53.406] Running "yarn run build"
[09:15:53.587] yarn run v1.22.19
[09:15:53.619] $ next build
[09:15:54.335] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[09:15:54.335] This information is used to shape Next.js' roadmap and prioritize features.
[09:15:54.336] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[09:15:54.336] https://nextjs.org/telemetry
[09:15:54.336] 
[09:15:54.401]   ▲ Next.js 14.2.4
[09:15:54.401] 
[09:15:54.472]    Creating an optimized production build ...
[09:16:48.372]  ✓ Compiled successfully
[09:16:48.374]    Linting and checking validity of types ...
[09:17:11.745]    Collecting page data ...
[09:17:14.222]    Generating static pages (0/4) ...
[09:17:16.435]    Generating static pages (1/4) 
[09:17:16.443]    Generating static pages (2/4) 
[09:17:17.123]    Generating static pages (3/4) 
[09:17:17.129] Invalid Value
[09:17:17.129] Error: Invalid Value
[09:17:17.130]     at y (/vercel/path0/.next/server/chunks/833.js:1:6731)
[09:17:17.130]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[09:17:17.130]     at async Promise.all (index 0)
[09:17:17.130]     at async l (/vercel/path0/.next/server/app/page.js:1:7755) {
[09:17:17.131]   digest: '23368453'
[09:17:17.131] }
[09:17:17.131] Invalid Value
[09:17:17.131] Invalid Value
[09:17:17.131] Error: Invalid Value
[09:17:17.131]     at y (/vercel/path0/.next/server/chunks/833.js:1:6731)
[09:17:17.131]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[09:17:17.132]     at async Promise.all (index 0)
[09:17:17.132]     at async l (/vercel/path0/.next/server/app/page.js:1:7755) {
[09:17:17.132]   digest: '23368453'
[09:17:17.132] }
[09:17:17.132] Error: Invalid Value
[09:17:17.132]     at y (/vercel/path0/.next/server/chunks/833.js:1:6731)
[09:17:17.132]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[09:17:17.132]     at async Promise.all (index 0)
[09:17:17.133]     at async l (/vercel/path0/.next/server/app/page.js:1:7755) {
[09:17:17.133]   digest: '23368453'
[09:17:17.133] }
[09:17:17.133] Invalid Value
[09:17:17.133] 
[09:17:17.134] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[09:17:17.134] 
[09:17:17.134] Error: Invalid Value
[09:17:17.134]     at y (/vercel/path0/.next/server/chunks/833.js:1:6731)
[09:17:17.134]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[09:17:17.134]     at async Promise.all (index 0)
[09:17:17.134]     at async l (/vercel/path0/.next/server/app/page.js:1:7755)
[09:17:17.137]  ✓ Generating static pages (4/4)
[09:17:17.166] 
[09:17:17.171] > Export encountered errors on following paths:
[09:17:17.171] 	/page: /
[09:17:17.269] error Command failed with exit code 1.
[09:17:17.269] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[09:17:17.293] Error: Command "yarn run build" exited with 1
[09:17:17.996]

**Comment by pk3011** [comment]
Make sure you've set the env inside Vercel deployment settings
If you're using the configurator, there's a bug where it generated the wrong encrypted root / shared drive ID. So you need to re-encrypt the ID yourself using the encrypt API routes. (https://drive-demo.mbaharip.com/api/internal/encrypt?q=<ID>&key=<ENCRYPTION_KEY>)

i did already but got above error.

**Comment by dandepan303** [comment]
Any updates on this issue?

**Comment by mbahArip** [comment]
Encryption method are updated in the latest version
You can try to update the repository, and read the [migration guide](https://drive-demo.mbaharip.com/ngdi-internal/deploy#migration)
