### ISSUE TITLE
Issue while deploying

### ISSUE THREAD

**Issue by NamasteIndia** [mbahArip/next-gdrive-index#29]
[14:11:48.524] Running build in Washington, D.C., USA (East) – iad1
[14:11:48.674] Cloning github.com/NamasteIndia/next-gdrive-index (Branch: main, Commit: fcdac1f)
[14:11:49.019] Previous build cache not available
[14:11:49.108] Cloning completed: 433.849ms
[14:11:49.383] Running "vercel build"
[14:11:49.835] Vercel CLI 35.2.3
[14:11:50.239] Installing dependencies...
[14:11:50.544] yarn install v1.22.19
[14:11:50.633] [1/4] Resolving packages...
[14:11:51.121] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog@5.0.1: This package is no longer supported.
[14:11:51.131] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[14:11:51.154] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog > gauge@3.0.2: This package is no longer supported.
[14:11:51.167] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > npmlog > are-we-there-yet@2.0.0: This package is no longer supported.
[14:11:51.198] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
[14:11:51.250] warning @cyntler/react-doc-viewer > react-pdf > pdfjs-dist > canvas > @mapbox/node-pre-gyp > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[14:11:55.083] warning googleapis > google-auth-library > gtoken > google-p12-pem@4.0.1: Package is no longer maintained
[14:12:02.274] warning eslint > @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
[14:12:02.317] warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[14:12:02.348] warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[14:12:03.926] [2/4] Fetching packages...
[14:12:33.211] [3/4] Linking dependencies...
[14:12:33.242] warning " > plyr-react@5.3.0" has unmet peer dependency "plyr@^3.7.7".
[14:12:33.243] warning "react-hot-toast > goober@2.1.14" has unmet peer dependency "csstype@^3.0.10".
[14:12:33.243] warning " > react-popper@2.3.0" has unmet peer dependency "@popperjs/core@^2.0.0".
[14:12:33.246] warning "eslint-config-next > @typescript-eslint/parser@7.2.0" has incorrect peer dependency "eslint@^8.56.0".
[14:12:45.156] [4/4] Building fresh packages...
[14:12:47.357] success Saved lockfile.
[14:12:47.366] Done in 56.83s.
[14:12:47.421] Detected Next.js version: 14.2.5
[14:12:47.423] Running "yarn run build"
[14:12:47.603] yarn run v1.22.19
[14:12:47.635] $ next build
[14:12:48.338] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[14:12:48.338] This information is used to shape Next.js' roadmap and prioritize features.
[14:12:48.339] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[14:12:48.339] https://nextjs.org/telemetry
[14:12:48.339] 
[14:12:48.401]   ▲ Next.js 14.2.5
[14:12:48.402] 
[14:12:48.472]    Creating an optimized production build ...
[14:13:42.339]  ✓ Compiled successfully
[14:13:42.340]    Linting and checking validity of types ...
[14:14:03.159]    Collecting page data ...
[14:14:05.483]    Generating static pages (0/4) ...
[14:14:07.652]    Generating static pages (1/4) 
[14:14:07.653]    Generating static pages (2/4) 
[14:14:08.224] error:1C800064:Provider routines::bad decrypt
[14:14:08.224] error:1C800064:Provider routines::bad decrypt
[14:14:08.224] Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.224] Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.224] error:1C800064:Provider routines::bad decrypt
[14:14:08.224] error:1C800064:Provider routines::bad decrypt
[14:14:08.225] Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.225] Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.225] Error: Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.225]     at y (/vercel/path0/.next/server/chunks/833.js:1:6731)
[14:14:08.225]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[14:14:08.225]     at runNextTicks (node:internal/process/task_queues:64:3)
[14:14:08.225]     at listOnTimeout (node:internal/timers:545:9)
[14:14:08.225]     at process.processTimers (node:internal/timers:519:7)
[14:14:08.225]     at async Promise.all (index 0)
[14:14:08.225]     at async l (/vercel/path0/.next/server/app/page.js:1:7755) {
[14:14:08.225]   digest: '617977668'
[14:14:08.225] }
[14:14:08.225] Error: Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.226]     at y (/vercel/path0/.next/server/chunks/833.js:1:6731)
[14:14:08.226]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[14:14:08.230]     at async Promise.all (index 0)
[14:14:08.230]     at async l (/vercel/path0/.next/server/app/page.js:1:7755) {
[14:14:08.230]   digest: '841613701'
[14:14:08.231] }
[14:14:08.231] Error: Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.231]     at y (/vercel/path0/.next/server/chunks/833.js:1:6731)
[14:14:08.231]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[14:14:08.231]     at async Promise.all (index 0)
[14:14:08.231]     at async l (/vercel/path0/.next/server/app/page.js:1:7755) {
[14:14:08.232]   digest: '841613701'
[14:14:08.232] }
[14:14:08.232] 
[14:14:08.232] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[14:14:08.232] 
[14:14:08.232] Error: Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.232]     at y (/vercel/path0/.next/server/chunks/833.js:1:6731)
[14:14:08.233]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[14:14:08.233]     at runNextTicks (node:internal/process/task_queues:64:3)
[14:14:08.233]     at listOnTimeout (node:internal/timers:545:9)
[14:14:08.233]     at process.processTimers (node:internal/timers:519:7)
[14:14:08.233]     at async Promise.all (index 0)
[14:14:08.233]     at async l (/vercel/path0/.next/server/app/page.js:1:7755)
[14:14:08.233]    Generating static pages (3/4) 
[14:14:08.234]  ✓ Generating static pages (4/4)
[14:14:08.239] 
[14:14:08.240] > Export encountered errors on following paths:
[14:14:08.240] 	/page: /
[14:14:08.358] error Command failed with exit code 1.
[14:14:08.358] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[14:14:08.385] Error: Command "yarn run build" exited with 1
[14:14:12.058]

**Comment by mbahArip** [comment]
```
[14:14:08.224] error:1C800064:Provider routines::bad decrypt
[14:14:08.224] error:1C800064:Provider routines::bad decrypt
[14:14:08.224] Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.224] Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.224] error:1C800064:Provider routines::bad decrypt
[14:14:08.224] error:1C800064:Provider routines::bad decrypt
[14:14:08.225] Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.225] Failed to decrypt data, either invalid hash or encryption key.
[14:14:08.225] Error: Failed to decrypt data, either invalid hash or encryption key.
```

Encrypted Root / Shared drive ID are incorrect
make sure you re-encrypt the plain root / shared id using this endpoint, then update your config
`https://drive-demo.mbaharip.com/api/internal/encrypt?q=<ID>&key=<ENCRYPTION_KEY>`

if the problem persist, try to redeploy without build cache

**Comment by CuriousMidnight** [comment]
i don't get it where to put the value that is given from the endpoint?

**Comment by mbahArip** [comment]
I'm currently fixing it, and implement some new feature.
I'll try my best to finish it before new year.
