### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by lma9to3** [mbahArip/next-gdrive-index#31]
Error: File not found: .
    at y (/vercel/path0/.next/server/chunks/833.js:1:6731)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async l (/vercel/path0/.next/server/app/page.js:1:7434) {
  digest: '1130917697'

**Comment by stag-enterprises** [comment]
I am also getting this issue, I am sure my configuration is correct but the error persists.

**Comment by Vinzgh25** [comment]
any chance to fix this problem?

**Comment by mbahArip** [comment]
I'm currently fixing it, and implement some new feature.
I'll try my best to finish it before new year.

**Comment by mbahArip** [comment]
Welp, it took a lot more than I expected.

Can you try version 2.0.4, and see if the problem is fixed?
You can check the [new deploying guide](https://drive-demo.mbaharip.com/ngdi-internal/deploy), if you already have your config you can go directly to `Migration` section

**Comment by stag-enterprises** [comment]
@mbahArip It works great for me! Thanks for your work on this project.
