### ISSUE TITLE
An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details.

### ISSUE THREAD

**Issue by mioscape** [mbahArip/next-gdrive-index#8]
# Console from vercel
![image](https://github.com/mbahArip/next-gdrive-index/assets/43681888/5fde4bd6-235e-4a48-b2c3-200298637054)

```
Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

# Console from local
```
File not found: .
Error: File not found: .
    at z (C:\Users\mioscape\personal-project\gdrive-index-next\.next\server\chunks\828.js:1:9907)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async m (C:\Users\mioscape\personal-project\gdrive-index-next\.next\server\app\page.js:1:3700)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '2853412524'
}
```

**Comment by mbahArip** [comment]
It is caused by either:
- wrong encrypted root folder ID
- wrong encryption key
- wrong base64 gd service / service account doesn't have access to the folder

**Comment by mbahArip** [comment]
Oh wait, my bad.

On [Migration Guide](https://github.com/mbahArip/next-gdrive-index?tab=readme-ov-file#migration-guide), I wrote to encrypt the folder ID on `https://drive-demo.mbaharip.com/api/internal/encrypt?q={{ folderId }}`

It should be on your localhost, instead of the demo site.
Since it will generate a encrypted root id based on my encryption key, not yours.

**Comment by mioscape** [comment]
Should i minify my service json?

**Comment by mioscape** [comment]
New error from local

```
error:1C800064:Provider routines::bad decrypt
error:1C800064:Provider routines::bad decrypt
Failed to decrypt data, either invalid hash or encryption key.
Failed to decrypt data, either invalid hash or encryption key.
Error: Failed to decrypt data, either invalid hash or encryption key.
    at b (C:\Users\mioscape\personal-project\gdrive-index-next\.next\server\chunks\828.js:1:6029)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async m (C:\Users\mioscape\personal-project\gdrive-index-next\.next\server\app\page.js:1:3700)
```

**Comment by mioscape** [comment]
My bad, i don't rebuild the app. It's working now. Thank you!
